---
- hosts: all
  become: true

  tasks:
  - name: Update all packages
    yum:
      name: '*'
      state: latest
      update_only: yes
    
  - name: Install Java 
    yum:
      name: java-1.8.0
      state: present
      update_cache: yes

  - name: Check Java version 
    command: sudo java --version
    register: java_version
  - debug:
      var: java_version.stderr
  
  - name: Import elasticsearch rpm key
    rpm_key:
      state: present
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  
  - name: Copy elasticsearch repo file
    copy:
      src: ./elasticsearch.repo
      dest: /etc/yum.repos.d/elasticsearch.repo

  - name: Check file elasticsearch repo location
    stat:
      path: /etc/yum.repos.d/elasticsearch.repo
    register: result
  - debug:
      var: result.stat.exists

  - name: Download Elasticsearch RPM
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-x86_64.rpm
      dest: /tmp/elasticsearch-7.15.2-x86_64.rpm
  
  - name: Download Elasticsearch SHA Key
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-x86_64.rpm.sha512
      dest: /tmp/elasticsearch-7.15.2-x86_64.rpm.sha512

  - name: Install Elasticsearch
    shell: sudo rpm --install /tmp/elasticsearch-7.15.2-x86_64.rpm

  - name: Copy elasticsearch config file
    copy:
      src: ./elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml
  
  - name: "Ensure elasticsearch network host is localhost"
    lineinfile:
      name: /etc/elasticsearch/elasticsearch.yml
      line: "network.host: 127.0.0.1"
      state: present
    check_mode: yes
    register: conf
  - debug:
      var: conf

  - name: Enable Elasticsearch service at startup
    service:
      name: elasticsearch
      state: started
      enabled: yes
  
  - name: Install Logstash
    yum:
      name: logstash
      state: present
      update_cache: yes

  - name: Copy apache config file
    copy:
      src: ./apache-01.conf
      dest: /etc/logstash/conf.d/apache-01.conf

  - name: Enable Logstash service at startup
    service:
      name: logstash
      state: started
      enabled: yes

  - name: Install kibana
    yum:
      name: kibana
      state: present
      update_cache: yes

  - name: Copy kibana config file
    copy:
      src: ./kibana.yml
      dest: /etc/kibana/kibana.yml

  - name: Enable kibana service at startup
    service:
      name: kibana
      state: started
      enabled: yes

  - name: Install filebeat
    yum:
      name: filebeat
      state: present
      update_cache: yes
  
  - name: Enable filebeat
    shell: sudo filebeat modules enable system


  
  
