---
- hosts: all
  become: true

  tasks:
  - name: Update all packages
    yum:
      name: '*'
      state: latest
      update_only: yes
    
  - name: Install Java 
    yum:
      name: java-1.8.0
      state: present
      update_cache: yes

  - name: Check Java version 
    command: sudo java -version
    register: java_version
  - debug:
      var: java_version.stderr
  
  - name: Import elasticsearch rpm key
    rpm_key:
      state: present
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  
  - name: Copy elasticsearch repo file
    copy:
      src: ./elasticsearch.repo
      dest: /etc/yum.repos.d/elasticsearch.repo

  - name: Check file elasticsearch repo location
    stat:
      path: /etc/yum.repos.d/elasticsearch.repo
    register: repo
  - debug:
      var: repo.stat.exists

  - name: Download Elasticsearch RPM
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-x86_64.rpm
      dest: /tmp/elasticsearch-7.15.2-x86_64.rpm

  - name: Check elasticsearch RPM file location 
    stat:
      path: /tmp/elasticsearch-7.15.2-x86_64.rpm
    register: rpm
  - debug:
      var: rpm.stat.exists
  
  - name: Download Elasticsearch SHA Key
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-x86_64.rpm.sha512
      dest: /tmp/elasticsearch-7.15.2-x86_64.rpm.sha512

  - name: Check elasticsearch SHA Key location
    stat:
      path: /tmp/elasticsearch-7.15.2-x86_64.rpm.sha512
    register: sha
  - debug:
      var: sha.stat.exists

  - name: Install Elasticsearch
    shell: sudo rpm --install /tmp/elasticsearch-7.15.2-x86_64.rpm

  - name: Copy elasticsearch config file
    copy:
      src: ./elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml
  
  - name: Check elasticsearch config file location
    stat:
      path: /tmp/elasticsearch-7.15.2-x86_64.rpm.sha512
    register: sha
  - debug:
      var: sha.stat.exists
  
  - name: "Ensure elasticsearch network host is localhost"
    lineinfile:
      name: /etc/elasticsearch/elasticsearch.yml
      line: "network.host: 127.0.0.1"
      state: present
    check_mode: yes
    register: host
  - debug:
      var: host.failed  

  - name: "Ensure elasticsearch http port is 9200"
    lineinfile:
      name: /etc/elasticsearch/elasticsearch.yml
      line: "http.port: 9200"
      state: present
    check_mode: yes
    register: port
  - debug:
      var: port.failed 

  - name: Enable Elasticsearch service at startup
    service:
      name: elasticsearch
      state: started
      enabled: yes
  
  - name: Install Logstash
    yum:
      name: logstash
      state: present
      update_cache: yes

  - name: Copy apache config file
    copy:
      src: ./apache-01.conf
      dest: /etc/logstash/conf.d/apache-01.conf

  - name: Check apache config file location
    stat:
      path: /etc/logstash/conf.d/apache-01.conf
    register: apache
  - debug:
      var: apache.stat.exists

  - name: Enable Logstash service at startup
    service:
      name: logstash
      state: started
      enabled: yes

  - name: Install kibana
    yum:
      name: kibana
      state: present
      update_cache: yes

  - name: Copy kibana config file
    copy:
      src: ./kibana.yml
      dest: /etc/kibana/kibana.yml

  - name: Check kibana config file location
    stat:
      path: /etc/kibana/kibana.yml
    register: kibana
  - debug:
      var: kibana.stat.exists

  - name: "Ensure elasticsearch host is configured"
    lineinfile:
      name: /etc/kibana/kibana.yml
      line: "http://localhost:9200"
      state: present
    check_mode: yes
    register: server_host
  - debug:
      var: serverhost.failed  

  - name: "Ensure kibana server port is 5601"
    lineinfile:
      name: /etc/kibana/kibana.yml
      line: "server.port: 5601"
      state: present
    check_mode: yes
    register: server_port
  - debug:
      var: server_port.failed 

  - name: Enable kibana service at startup
    service:
      name: kibana
      state: started
      enabled: yes

  - name: Install filebeat
    yum:
      name: filebeat
      state: present
      update_cache: yes
  
  - name: Enable filebeat
    shell: sudo filebeat modules enable system

  - name: Check ELK services status
    service_facts:
    register: elk_state
  - debug:
      var: elk_state.ansible_facts.services['elasticsearch.service']
  - debug:
      var: elk_state.ansible_facts.services['logstash.service']
  - debug:
      var: elk_state.ansible_facts.services['kibana.service']

  
  
