---
- name: Install Elasticsearch (Amazon)
  ansible.builtin.shell: sudo rpm --install /tmp/elasticsearch-7.15.2-x86_64.rpm
  when: ansible_distribution == "Amazon"
  notify:
    - Enable Elasticsearch service at startup
  
- name: Install Elasticsearch (Ubuntu)
  ansible.builtin.apt:
    name: elasticsearch
    state: present
    update_cache: true
  when: ansible_distribution == "Ubuntu"
  notify:
    - Enable Elasticsearch service at startup

- name: Copy elasticsearch config file
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify:
    - Restart Elasticsearch service

- name: Check elasticsearch config file location
  ansible.builtin.stat:
    path: /etc/elasticsearch/elasticsearch.yml
  register: elastic
- ansible.builtin.debug:
    var: elastic.stat.exists
  
- name: Ensure elasticsearch network host is localhost
  ansible.builtin.lineinfile:
    name: /etc/elasticsearch/elasticsearch.yml
    line: "network.host: 127.0.0.1"
    state: present
  check_mode: true
  register: host
- ansible.builtin.debug:
    var: host.failed  

- name: Ensure elasticsearch http port is 9200
  ansible.builtin.lineinfile:
    name: /etc/elasticsearch/elasticsearch.yml
    line: "http.port: 9200"
    state: present
  check_mode: true
  register: port
- ansible.builtin.debug:
    var: port.failed 