---
# handlers file for elasticsearch
- name: Enable Elasticsearch service at startup
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: true

- name: Restart Elasticsearch service
  ansible.builtin.service:
    name: elasticsearch
    state: restarted