---
- name: Import elasticsearch rpm key (centos)
  rpm_key:
    state: present
    key: "{{elastic.rpm_key}}"
  when: linux_distribution == "centos"

- name: Copy elasticsearch repo file (centos)
  copy:
    src: ./elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
  when: linux_distribution == "centos"

- name: Download Elasticsearch RPM (centos)
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{elastic.version}}.rpm
    dest: /tmp/elasticsearch-{{elastic.version}}.rpm
  when: linux_distribution == "centos"

- name: Download Elasticsearch SHA Key (centos)
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{elastic.version}}.rpm.sha512
    dest: /tmp/elasticsearch-{{elastic.version}}.rpm.sha512
  when: linux_distribution == "centos"

- name: Import Elasticsearch PGP Key (ubuntu)
  shell: wget -qO - {{elastic.rpm_key}}" | sudo apt-key add -
  when: linux_distribution == "ubuntu"

- name: Add repository definition (ubuntu)
  copy:
    dest: /etc/apt/sources.list.d/elastic-7.x.list
    content: |
      deb https://artifacts.elastic.co/packages/7.x/apt stable main
  when: linux_distribution == "ubuntu"

- name: update cache and ignore errors in case of problems (ubuntu)
  apt: 
    update_cache: yes
    ignore_errors: yes
  when: linux_distribution == "ubuntu"