---
- name: Install Elasticsearch (centos)
  shell: sudo rpm --install /tmp/elasticsearch-7.15.2-x86_64.rpm
  when: linux_distribution == "centos"
  notify:
    - Enable Elasticsearch service at startup
  
- name: Install Elasticsearch (ubuntu)
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
  when: linux_distribution == "ubuntu"
  notify:
    - Enable Elasticsearch service at startup

- name: Copy elasticsearch config file
  copy:
    src: ./elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
  notify:
    - Restart Elasticsearch service