---
- name: Install kibana (centos)
  yum:
    name: kibana
    state: present
    update_cache: yes
  when: linux_distribution == "centos"
  notify:
    - Enable Kibana service at startup

- name: Install kibana (ubuntu)
  apt:
    name: kibana
    state: present
  when: linux_distribution == "ubuntu"
  notify:
    - Enable Kibana service at startup

- name: Copy kibana config file
  copy:
    src: ./files/kibana.yml
    dest: /etc/kibana/kibana.yml
  notify:
    - Restart Kibana service