variable "AVAILABILITY_ZONE" {}
variable "SG_VPC_ID" {}
variable "SG_NAME" {}
variable "SG_DESCRIPTION" {}
variable "AMI_ID" {}
variable "INSTANCE_TYPE" {}
variable "INSTANCE_NAME" {}
variable "VPC_SECURITY_GROUP_IDS" {}
variable "INSTANCE_USERNAME" {}
